part-2-testing
Lev-Excellenteam-2023/exercise3-chess-check-AdielDror pull request #1
Opened 2023-05-04 18:11 UTC by AdielDror

I added tests

2023-05-15 07:42 UTC, talbarfm commented on chess_gui.py
> +                                logger.info("The white player started first.")
The question is if the computer started or the player

2023-05-15 07:42 UTC, talbarfm commented on chess_gui.py
> +            logger.info("Black is wins!")
Add more logs to the endgame

2023-05-15 07:43 UTC, talbarfm requested changes
Please note that you have to separate the pull requests.

2023-05-29 10:19 UTC, talbarfm commented on Tests/test_4Piece.py
> +                          [(), (), (), (), (), (), (), ()]]
Use mocks, or create an initialization function

2023-05-29 10:20 UTC, talbarfm commented on Tests/test_4Piece.py
> +    black_king = King('k', 7, 3, Player.PLAYER_2)
There's a better way to initialize the game

2023-06-01 21:25 UTC, AdielDror commented on Tests/test_4Piece.py
> +                          [(), (), (), (), (), (), (), ()]]
I fixed it

2023-06-01 21:25 UTC, AdielDror commented on Tests/test_4Piece.py
> +    black_king = King('k', 7, 3, Player.PLAYER_2)
I fixed it.

2023-08-12 20:42 UTC, merged